version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=joe
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=memory
  web:
    build: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8001
    volumes:
      - ./backend:/code
      - "${PROJECT_DIRECTORY}:${PROJECT_DIRECTORY}"
    ports:
      - 8001:8001
    depends_on:
      - db
    env_file:
      - ./backend/.env
    environment:
      - CODEAPP_DB_HOST=db
    user: root
  frontend:
    build: ./frontend
    environment:
      - PORT=5000
      - NEXT_PUBLIC_API_URL=http://localhost:8001
    ports:
      - 5000:5000
    command: npm run dev
    volumes:
      - ./frontend:/app
    depends_on:
      - web
volumes:
  postgres_data:
